#!/usr/bin/env node
/**
 * scripts/generate-api.mjs
 *
 * Regenerates src/api/generated/ from the BE OpenAPI 3.1 schema.
 *
 * Usage:
 *   npm run generate:api            — regenerate in place
 *   npm run generate:api -- --check — CI drift check (exit 1 on diff)
 *
 * Source resolution order:
 *   1. VITE_OPENAPI_URL (live BE)
 *   2. docs/openapi.snapshot.json  (committed fallback)
 *   3. exit 1 with actionable message
 */

import { execSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')

const GENERATED_DIR = join(ROOT, 'src', 'api', 'generated')
const SCHEMA_OUT = join(GENERATED_DIR, 'schema.ts')
const INDEX_OUT = join(GENERATED_DIR, 'index.ts')
const SNAPSHOT_PATH = join(ROOT, 'docs', 'openapi.snapshot.json')
const DEFAULT_OPENAPI_URL = 'http://localhost:8000/api/v1/openapi.json'

const CHECK_MODE = process.argv.includes('--check')

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function log(msg) {
  process.stdout.write(`[generate:api] ${msg}\n`)
}

function die(msg) {
  process.stderr.write(`[generate:api] ERROR: ${msg}\n`)
  process.exit(1)
}

async function isUrlReachable(url) {
  try {
    const res = await fetch(url, { method: 'HEAD', signal: AbortSignal.timeout(5000) })
    return res.ok
  } catch {
    return false
  }
}

// ---------------------------------------------------------------------------
// Resolve schema source
// ---------------------------------------------------------------------------

const openApiUrl = process.env.VITE_OPENAPI_URL || DEFAULT_OPENAPI_URL
let schemaSource

log(`checking live source: ${openApiUrl}`)
if (await isUrlReachable(openApiUrl)) {
  schemaSource = openApiUrl
  log(`source=${schemaSource}`)
} else if (existsSync(SNAPSHOT_PATH)) {
  schemaSource = SNAPSHOT_PATH
  log(`live source unreachable — falling back to ${SNAPSHOT_PATH}`)
} else {
  die(
    `could not load OpenAPI schema (tried ${openApiUrl} and docs/openapi.snapshot.json). ` +
      'Start BE or commit a snapshot.',
  )
}

// ---------------------------------------------------------------------------
// Run openapi-typescript
// ---------------------------------------------------------------------------

mkdirSync(GENERATED_DIR, { recursive: true })

if (CHECK_MODE) {
  // Regenerate into a temp file and compare to the committed file.
  const tmpSchema = join(tmpdir(), `ilex-schema-check-${Date.now()}.ts`)
  try {
    execSync(`npx openapi-typescript "${schemaSource}" -o "${tmpSchema}"`, {
      stdio: ['ignore', 'ignore', 'inherit'],
      cwd: ROOT,
    })
  } catch {
    die('openapi-typescript failed during --check run')
  }

  if (!existsSync(SCHEMA_OUT)) {
    die('src/api/generated/schema.ts does not exist. Run `npm run generate:api` first.')
  }

  const committed = readFileSync(SCHEMA_OUT, 'utf8')
  const generated = readFileSync(tmpSchema, 'utf8')

  if (committed === generated) {
    log('OK: generated client matches schema')
    process.exit(0)
  } else {
    // Show first 40 lines of diff (best-effort; diff may not be installed everywhere)
    try {
      const diff = execSync(`diff "${SCHEMA_OUT}" "${tmpSchema}" | head -40`, {
        encoding: 'utf8',
        stdio: ['ignore', 'pipe', 'ignore'],
      })
      process.stderr.write(diff)
    } catch {
      // diff exits 1 on differences — that's expected; ignore the error
    }
    die('DRIFT: run `npm run generate:api`')
  }
} else {
  // Normal regeneration.
  try {
    execSync(`npx openapi-typescript "${schemaSource}" -o "${SCHEMA_OUT}"`, {
      stdio: 'inherit',
      cwd: ROOT,
    })
  } catch {
    die('openapi-typescript failed')
  }

  // Count paths in the generated file (approximation: count "paths:" occurrences)
  const generatedContent = readFileSync(SCHEMA_OUT, 'utf8')
  const pathCount = (generatedContent.match(/^\s+["']\/api\//gm) || []).length

  log(`wrote src/api/generated/schema.ts (${pathCount} paths)`)

  // Write the thin index re-exporter.
  writeFileSync(
    INDEX_OUT,
    `/**
 * src/api/generated/index.ts
 *
 * Re-exports the generated types for the data layer.
 * This file is committed and regenerated by \`npm run generate:api\`.
 * DO NOT edit by hand.
 */
export type { paths, components } from './schema'
`,
  )
  log('wrote src/api/generated/index.ts')
}
