/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed.index'
import { Route as AuthedStockRouteImport } from './routes/_authed.stock'
import { Route as AuthedSettingsRouteImport } from './routes/_authed.settings'
import { Route as AuthedSalesOrdersIndexRouteImport } from './routes/_authed.sales-orders.index'
import { Route as AuthedPurchaseOrdersIndexRouteImport } from './routes/_authed.purchase-orders.index'
import { Route as AuthedProductsIndexRouteImport } from './routes/_authed.products.index'
import { Route as AuthedSalesOrdersNewRouteImport } from './routes/_authed.sales-orders.new'
import { Route as AuthedSalesOrdersIdRouteImport } from './routes/_authed.sales-orders.$id'
import { Route as AuthedPurchaseOrdersNewRouteImport } from './routes/_authed.purchase-orders.new'
import { Route as AuthedPurchaseOrdersIdRouteImport } from './routes/_authed.purchase-orders.$id'
import { Route as AuthedProductsIdRouteImport } from './routes/_authed.products.$id'
import { Route as AuthedBatchesIdRouteImport } from './routes/_authed.batches.$id'
import { Route as AuthedSalesOrdersIdIndexRouteImport } from './routes/_authed.sales-orders.$id.index'
import { Route as AuthedSalesOrdersIdEditRouteImport } from './routes/_authed.sales-orders.$id.edit'
import { Route as AuthedPurchaseOrdersIdEditRouteImport } from './routes/_authed.purchase-orders.$id.edit'
import { Route as AuthedBatchesIdRecallReportRouteImport } from './routes/_authed.batches.$id.recall-report'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStockRoute = AuthedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSalesOrdersIndexRoute = AuthedSalesOrdersIndexRouteImport.update({
  id: '/sales-orders/',
  path: '/sales-orders/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPurchaseOrdersIndexRoute =
  AuthedPurchaseOrdersIndexRouteImport.update({
    id: '/purchase-orders/',
    path: '/purchase-orders/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedProductsIndexRoute = AuthedProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSalesOrdersNewRoute = AuthedSalesOrdersNewRouteImport.update({
  id: '/sales-orders/new',
  path: '/sales-orders/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSalesOrdersIdRoute = AuthedSalesOrdersIdRouteImport.update({
  id: '/sales-orders/$id',
  path: '/sales-orders/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPurchaseOrdersNewRoute = AuthedPurchaseOrdersNewRouteImport.update({
  id: '/purchase-orders/new',
  path: '/purchase-orders/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPurchaseOrdersIdRoute = AuthedPurchaseOrdersIdRouteImport.update({
  id: '/purchase-orders/$id',
  path: '/purchase-orders/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsIdRoute = AuthedProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBatchesIdRoute = AuthedBatchesIdRouteImport.update({
  id: '/batches/$id',
  path: '/batches/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSalesOrdersIdIndexRoute =
  AuthedSalesOrdersIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedSalesOrdersIdRoute,
  } as any)
const AuthedSalesOrdersIdEditRoute = AuthedSalesOrdersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AuthedSalesOrdersIdRoute,
} as any)
const AuthedPurchaseOrdersIdEditRoute =
  AuthedPurchaseOrdersIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthedPurchaseOrdersIdRoute,
  } as any)
const AuthedBatchesIdRecallReportRoute =
  AuthedBatchesIdRecallReportRouteImport.update({
    id: '/recall-report',
    path: '/recall-report',
    getParentRoute: () => AuthedBatchesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/settings': typeof AuthedSettingsRoute
  '/stock': typeof AuthedStockRoute
  '/batches/$id': typeof AuthedBatchesIdRouteWithChildren
  '/products/$id': typeof AuthedProductsIdRoute
  '/purchase-orders/$id': typeof AuthedPurchaseOrdersIdRouteWithChildren
  '/purchase-orders/new': typeof AuthedPurchaseOrdersNewRoute
  '/sales-orders/$id': typeof AuthedSalesOrdersIdRouteWithChildren
  '/sales-orders/new': typeof AuthedSalesOrdersNewRoute
  '/products/': typeof AuthedProductsIndexRoute
  '/purchase-orders/': typeof AuthedPurchaseOrdersIndexRoute
  '/sales-orders/': typeof AuthedSalesOrdersIndexRoute
  '/batches/$id/recall-report': typeof AuthedBatchesIdRecallReportRoute
  '/purchase-orders/$id/edit': typeof AuthedPurchaseOrdersIdEditRoute
  '/sales-orders/$id/edit': typeof AuthedSalesOrdersIdEditRoute
  '/sales-orders/$id/': typeof AuthedSalesOrdersIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/settings': typeof AuthedSettingsRoute
  '/stock': typeof AuthedStockRoute
  '/': typeof AuthedIndexRoute
  '/batches/$id': typeof AuthedBatchesIdRouteWithChildren
  '/products/$id': typeof AuthedProductsIdRoute
  '/purchase-orders/$id': typeof AuthedPurchaseOrdersIdRouteWithChildren
  '/purchase-orders/new': typeof AuthedPurchaseOrdersNewRoute
  '/sales-orders/new': typeof AuthedSalesOrdersNewRoute
  '/products': typeof AuthedProductsIndexRoute
  '/purchase-orders': typeof AuthedPurchaseOrdersIndexRoute
  '/sales-orders': typeof AuthedSalesOrdersIndexRoute
  '/batches/$id/recall-report': typeof AuthedBatchesIdRecallReportRoute
  '/purchase-orders/$id/edit': typeof AuthedPurchaseOrdersIdEditRoute
  '/sales-orders/$id/edit': typeof AuthedSalesOrdersIdEditRoute
  '/sales-orders/$id': typeof AuthedSalesOrdersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/stock': typeof AuthedStockRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/batches/$id': typeof AuthedBatchesIdRouteWithChildren
  '/_authed/products/$id': typeof AuthedProductsIdRoute
  '/_authed/purchase-orders/$id': typeof AuthedPurchaseOrdersIdRouteWithChildren
  '/_authed/purchase-orders/new': typeof AuthedPurchaseOrdersNewRoute
  '/_authed/sales-orders/$id': typeof AuthedSalesOrdersIdRouteWithChildren
  '/_authed/sales-orders/new': typeof AuthedSalesOrdersNewRoute
  '/_authed/products/': typeof AuthedProductsIndexRoute
  '/_authed/purchase-orders/': typeof AuthedPurchaseOrdersIndexRoute
  '/_authed/sales-orders/': typeof AuthedSalesOrdersIndexRoute
  '/_authed/batches/$id/recall-report': typeof AuthedBatchesIdRecallReportRoute
  '/_authed/purchase-orders/$id/edit': typeof AuthedPurchaseOrdersIdEditRoute
  '/_authed/sales-orders/$id/edit': typeof AuthedSalesOrdersIdEditRoute
  '/_authed/sales-orders/$id/': typeof AuthedSalesOrdersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/settings'
    | '/stock'
    | '/batches/$id'
    | '/products/$id'
    | '/purchase-orders/$id'
    | '/purchase-orders/new'
    | '/sales-orders/$id'
    | '/sales-orders/new'
    | '/products/'
    | '/purchase-orders/'
    | '/sales-orders/'
    | '/batches/$id/recall-report'
    | '/purchase-orders/$id/edit'
    | '/sales-orders/$id/edit'
    | '/sales-orders/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/settings'
    | '/stock'
    | '/'
    | '/batches/$id'
    | '/products/$id'
    | '/purchase-orders/$id'
    | '/purchase-orders/new'
    | '/sales-orders/new'
    | '/products'
    | '/purchase-orders'
    | '/sales-orders'
    | '/batches/$id/recall-report'
    | '/purchase-orders/$id/edit'
    | '/sales-orders/$id/edit'
    | '/sales-orders/$id'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/settings'
    | '/_authed/stock'
    | '/_authed/'
    | '/_authed/batches/$id'
    | '/_authed/products/$id'
    | '/_authed/purchase-orders/$id'
    | '/_authed/purchase-orders/new'
    | '/_authed/sales-orders/$id'
    | '/_authed/sales-orders/new'
    | '/_authed/products/'
    | '/_authed/purchase-orders/'
    | '/_authed/sales-orders/'
    | '/_authed/batches/$id/recall-report'
    | '/_authed/purchase-orders/$id/edit'
    | '/_authed/sales-orders/$id/edit'
    | '/_authed/sales-orders/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stock': {
      id: '/_authed/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthedStockRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sales-orders/': {
      id: '/_authed/sales-orders/'
      path: '/sales-orders'
      fullPath: '/sales-orders/'
      preLoaderRoute: typeof AuthedSalesOrdersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/purchase-orders/': {
      id: '/_authed/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof AuthedPurchaseOrdersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products/': {
      id: '/_authed/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthedProductsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sales-orders/new': {
      id: '/_authed/sales-orders/new'
      path: '/sales-orders/new'
      fullPath: '/sales-orders/new'
      preLoaderRoute: typeof AuthedSalesOrdersNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sales-orders/$id': {
      id: '/_authed/sales-orders/$id'
      path: '/sales-orders/$id'
      fullPath: '/sales-orders/$id'
      preLoaderRoute: typeof AuthedSalesOrdersIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/purchase-orders/new': {
      id: '/_authed/purchase-orders/new'
      path: '/purchase-orders/new'
      fullPath: '/purchase-orders/new'
      preLoaderRoute: typeof AuthedPurchaseOrdersNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/purchase-orders/$id': {
      id: '/_authed/purchase-orders/$id'
      path: '/purchase-orders/$id'
      fullPath: '/purchase-orders/$id'
      preLoaderRoute: typeof AuthedPurchaseOrdersIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products/$id': {
      id: '/_authed/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthedProductsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/batches/$id': {
      id: '/_authed/batches/$id'
      path: '/batches/$id'
      fullPath: '/batches/$id'
      preLoaderRoute: typeof AuthedBatchesIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sales-orders/$id/': {
      id: '/_authed/sales-orders/$id/'
      path: '/'
      fullPath: '/sales-orders/$id/'
      preLoaderRoute: typeof AuthedSalesOrdersIdIndexRouteImport
      parentRoute: typeof AuthedSalesOrdersIdRoute
    }
    '/_authed/sales-orders/$id/edit': {
      id: '/_authed/sales-orders/$id/edit'
      path: '/edit'
      fullPath: '/sales-orders/$id/edit'
      preLoaderRoute: typeof AuthedSalesOrdersIdEditRouteImport
      parentRoute: typeof AuthedSalesOrdersIdRoute
    }
    '/_authed/purchase-orders/$id/edit': {
      id: '/_authed/purchase-orders/$id/edit'
      path: '/edit'
      fullPath: '/purchase-orders/$id/edit'
      preLoaderRoute: typeof AuthedPurchaseOrdersIdEditRouteImport
      parentRoute: typeof AuthedPurchaseOrdersIdRoute
    }
    '/_authed/batches/$id/recall-report': {
      id: '/_authed/batches/$id/recall-report'
      path: '/recall-report'
      fullPath: '/batches/$id/recall-report'
      preLoaderRoute: typeof AuthedBatchesIdRecallReportRouteImport
      parentRoute: typeof AuthedBatchesIdRoute
    }
  }
}

interface AuthedBatchesIdRouteChildren {
  AuthedBatchesIdRecallReportRoute: typeof AuthedBatchesIdRecallReportRoute
}

const AuthedBatchesIdRouteChildren: AuthedBatchesIdRouteChildren = {
  AuthedBatchesIdRecallReportRoute: AuthedBatchesIdRecallReportRoute,
}

const AuthedBatchesIdRouteWithChildren = AuthedBatchesIdRoute._addFileChildren(
  AuthedBatchesIdRouteChildren,
)

interface AuthedPurchaseOrdersIdRouteChildren {
  AuthedPurchaseOrdersIdEditRoute: typeof AuthedPurchaseOrdersIdEditRoute
}

const AuthedPurchaseOrdersIdRouteChildren: AuthedPurchaseOrdersIdRouteChildren =
  {
    AuthedPurchaseOrdersIdEditRoute: AuthedPurchaseOrdersIdEditRoute,
  }

const AuthedPurchaseOrdersIdRouteWithChildren =
  AuthedPurchaseOrdersIdRoute._addFileChildren(
    AuthedPurchaseOrdersIdRouteChildren,
  )

interface AuthedSalesOrdersIdRouteChildren {
  AuthedSalesOrdersIdEditRoute: typeof AuthedSalesOrdersIdEditRoute
  AuthedSalesOrdersIdIndexRoute: typeof AuthedSalesOrdersIdIndexRoute
}

const AuthedSalesOrdersIdRouteChildren: AuthedSalesOrdersIdRouteChildren = {
  AuthedSalesOrdersIdEditRoute: AuthedSalesOrdersIdEditRoute,
  AuthedSalesOrdersIdIndexRoute: AuthedSalesOrdersIdIndexRoute,
}

const AuthedSalesOrdersIdRouteWithChildren =
  AuthedSalesOrdersIdRoute._addFileChildren(AuthedSalesOrdersIdRouteChildren)

interface AuthedRouteChildren {
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedStockRoute: typeof AuthedStockRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedBatchesIdRoute: typeof AuthedBatchesIdRouteWithChildren
  AuthedProductsIdRoute: typeof AuthedProductsIdRoute
  AuthedPurchaseOrdersIdRoute: typeof AuthedPurchaseOrdersIdRouteWithChildren
  AuthedPurchaseOrdersNewRoute: typeof AuthedPurchaseOrdersNewRoute
  AuthedSalesOrdersIdRoute: typeof AuthedSalesOrdersIdRouteWithChildren
  AuthedSalesOrdersNewRoute: typeof AuthedSalesOrdersNewRoute
  AuthedProductsIndexRoute: typeof AuthedProductsIndexRoute
  AuthedPurchaseOrdersIndexRoute: typeof AuthedPurchaseOrdersIndexRoute
  AuthedSalesOrdersIndexRoute: typeof AuthedSalesOrdersIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedStockRoute: AuthedStockRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedBatchesIdRoute: AuthedBatchesIdRouteWithChildren,
  AuthedProductsIdRoute: AuthedProductsIdRoute,
  AuthedPurchaseOrdersIdRoute: AuthedPurchaseOrdersIdRouteWithChildren,
  AuthedPurchaseOrdersNewRoute: AuthedPurchaseOrdersNewRoute,
  AuthedSalesOrdersIdRoute: AuthedSalesOrdersIdRouteWithChildren,
  AuthedSalesOrdersNewRoute: AuthedSalesOrdersNewRoute,
  AuthedProductsIndexRoute: AuthedProductsIndexRoute,
  AuthedPurchaseOrdersIndexRoute: AuthedPurchaseOrdersIndexRoute,
  AuthedSalesOrdersIndexRoute: AuthedSalesOrdersIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
