/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed.index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed.settings'
import { Route as AuthedPurchaseOrdersIndexRouteImport } from './routes/_authed.purchase-orders.index'
import { Route as AuthedProductsIndexRouteImport } from './routes/_authed.products.index'
import { Route as AuthedPurchaseOrdersNewRouteImport } from './routes/_authed.purchase-orders.new'
import { Route as AuthedPurchaseOrdersIdRouteImport } from './routes/_authed.purchase-orders.$id'
import { Route as AuthedProductsIdRouteImport } from './routes/_authed.products.$id'
import { Route as AuthedPurchaseOrdersIdEditRouteImport } from './routes/_authed.purchase-orders.$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPurchaseOrdersIndexRoute =
  AuthedPurchaseOrdersIndexRouteImport.update({
    id: '/purchase-orders/',
    path: '/purchase-orders/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedProductsIndexRoute = AuthedProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPurchaseOrdersNewRoute = AuthedPurchaseOrdersNewRouteImport.update({
  id: '/purchase-orders/new',
  path: '/purchase-orders/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPurchaseOrdersIdRoute = AuthedPurchaseOrdersIdRouteImport.update({
  id: '/purchase-orders/$id',
  path: '/purchase-orders/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsIdRoute = AuthedProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPurchaseOrdersIdEditRoute =
  AuthedPurchaseOrdersIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthedPurchaseOrdersIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/settings': typeof AuthedSettingsRoute
  '/products/$id': typeof AuthedProductsIdRoute
  '/purchase-orders/$id': typeof AuthedPurchaseOrdersIdRouteWithChildren
  '/purchase-orders/new': typeof AuthedPurchaseOrdersNewRoute
  '/products/': typeof AuthedProductsIndexRoute
  '/purchase-orders/': typeof AuthedPurchaseOrdersIndexRoute
  '/purchase-orders/$id/edit': typeof AuthedPurchaseOrdersIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/settings': typeof AuthedSettingsRoute
  '/': typeof AuthedIndexRoute
  '/products/$id': typeof AuthedProductsIdRoute
  '/purchase-orders/$id': typeof AuthedPurchaseOrdersIdRouteWithChildren
  '/purchase-orders/new': typeof AuthedPurchaseOrdersNewRoute
  '/products': typeof AuthedProductsIndexRoute
  '/purchase-orders': typeof AuthedPurchaseOrdersIndexRoute
  '/purchase-orders/$id/edit': typeof AuthedPurchaseOrdersIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/products/$id': typeof AuthedProductsIdRoute
  '/_authed/purchase-orders/$id': typeof AuthedPurchaseOrdersIdRouteWithChildren
  '/_authed/purchase-orders/new': typeof AuthedPurchaseOrdersNewRoute
  '/_authed/products/': typeof AuthedProductsIndexRoute
  '/_authed/purchase-orders/': typeof AuthedPurchaseOrdersIndexRoute
  '/_authed/purchase-orders/$id/edit': typeof AuthedPurchaseOrdersIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/settings'
    | '/products/$id'
    | '/purchase-orders/$id'
    | '/purchase-orders/new'
    | '/products/'
    | '/purchase-orders/'
    | '/purchase-orders/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/settings'
    | '/'
    | '/products/$id'
    | '/purchase-orders/$id'
    | '/purchase-orders/new'
    | '/products'
    | '/purchase-orders'
    | '/purchase-orders/$id/edit'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/settings'
    | '/_authed/'
    | '/_authed/products/$id'
    | '/_authed/purchase-orders/$id'
    | '/_authed/purchase-orders/new'
    | '/_authed/products/'
    | '/_authed/purchase-orders/'
    | '/_authed/purchase-orders/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/purchase-orders/': {
      id: '/_authed/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof AuthedPurchaseOrdersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products/': {
      id: '/_authed/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthedProductsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/purchase-orders/new': {
      id: '/_authed/purchase-orders/new'
      path: '/purchase-orders/new'
      fullPath: '/purchase-orders/new'
      preLoaderRoute: typeof AuthedPurchaseOrdersNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/purchase-orders/$id': {
      id: '/_authed/purchase-orders/$id'
      path: '/purchase-orders/$id'
      fullPath: '/purchase-orders/$id'
      preLoaderRoute: typeof AuthedPurchaseOrdersIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products/$id': {
      id: '/_authed/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthedProductsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/purchase-orders/$id/edit': {
      id: '/_authed/purchase-orders/$id/edit'
      path: '/edit'
      fullPath: '/purchase-orders/$id/edit'
      preLoaderRoute: typeof AuthedPurchaseOrdersIdEditRouteImport
      parentRoute: typeof AuthedPurchaseOrdersIdRoute
    }
  }
}

interface AuthedPurchaseOrdersIdRouteChildren {
  AuthedPurchaseOrdersIdEditRoute: typeof AuthedPurchaseOrdersIdEditRoute
}

const AuthedPurchaseOrdersIdRouteChildren: AuthedPurchaseOrdersIdRouteChildren =
  {
    AuthedPurchaseOrdersIdEditRoute: AuthedPurchaseOrdersIdEditRoute,
  }

const AuthedPurchaseOrdersIdRouteWithChildren =
  AuthedPurchaseOrdersIdRoute._addFileChildren(
    AuthedPurchaseOrdersIdRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedProductsIdRoute: typeof AuthedProductsIdRoute
  AuthedPurchaseOrdersIdRoute: typeof AuthedPurchaseOrdersIdRouteWithChildren
  AuthedPurchaseOrdersNewRoute: typeof AuthedPurchaseOrdersNewRoute
  AuthedProductsIndexRoute: typeof AuthedProductsIndexRoute
  AuthedPurchaseOrdersIndexRoute: typeof AuthedPurchaseOrdersIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedProductsIdRoute: AuthedProductsIdRoute,
  AuthedPurchaseOrdersIdRoute: AuthedPurchaseOrdersIdRouteWithChildren,
  AuthedPurchaseOrdersNewRoute: AuthedPurchaseOrdersNewRoute,
  AuthedProductsIndexRoute: AuthedProductsIndexRoute,
  AuthedPurchaseOrdersIndexRoute: AuthedPurchaseOrdersIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
