import { createRouter } from '@tanstack/react-router'
import { QueryClient } from '@tanstack/react-query'
import { routeTree } from './routeTree.gen'

/**
 * Shared QueryClient — exported for use in the root route provider.
 * Per-test instances are created fresh in src/test/render.tsx.
 */
export const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 30_000, // 30 seconds
      retry: 1,
    },
  },
})

/**
 * TanStack Router instance.
 * routeTree.gen.ts is generated by @tanstack/router-plugin on dev server start.
 * Committed so first run isn't dependent on plugin codegen.
 *
 * defaultPreload: 'intent' — preloads routes on hover/focus for snappy navigation.
 */
export const router = createRouter({
  routeTree,
  defaultPreload: 'intent',
})

// Type-safe router registration for TanStack Router
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}
